# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MTC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTC
  rn_path = '../node_modules/react-native'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'FBSDKCoreKit', '~> 5.6.0'
  pod 'FBSDKLoginKit', '~> 5.6.0'
  pod 'FBSDKShareKit', '~> 5.6.0'
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/AdMob', '~> 5.20.1'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  pod 'Paystack'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  #pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-background-upload', :path => '../node_modules/react-native-background-upload'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-ffmpeg/min', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'react-native-apple-authentication', :path => '../node_modules/react-native-apple-authentication'

  target 'MTCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MTC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTC-tvOS

  target 'MTC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # if target.name == 'react-native-google-maps'
    #   target.build_configurations.each do |config|
    #     config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
    #   end
    # end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
